eureka:
  client:
    register-with-eureka: false

server:
  port: 8085

spring:

  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: students
          url: http://localhost:8090
          predicates:
            # Se agrega doble asterisco para indicarle que puede acceder
            - Path=/api/v1/student/**
        - id: courses
          url: http://localhost:9090
          predicates:
            # Se agrega doble asterisco para indicarle que puede acceder
            - Path=/api/v1/course/**